models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import ForeignKey


db = SQLAlchemy()


class User(db.Model, UserMixin):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), nullable=False, unique=True)
    password = db.Column(db.String(80), nullable=False)
    stats = db.relationship("Stats", back_populates="user",
                            uselist=False, cascade="all, delete-orphan")


class Stats(db.Model):
    __tablename__ = "stats"
    id = db.Column(db.Integer, ForeignKey(User.id), primary_key=True)
    money = db.Column(db.BigInteger, nullable=False)
    user = db.relationship("User", back_populates="stats")

forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError

from models import User


class LoginForm(FlaskForm):
    username = StringField(validators=[InputRequired(), Length(
        min=4, max=20)], render_kw={"placeholder": "Username"})

    password = PasswordField(validators=[InputRequired(), Length(
        min=4, max=20)], render_kw={"placeholder": "Password"})

    submit = SubmitField("Login")


class RegisterForm(FlaskForm):
    username = StringField(validators=[InputRequired(), Length(
        min=4, max=20)], render_kw={"placeholder": "Username"})

    password = PasswordField(validators=[InputRequired(), Length(
        min=4, max=20)], render_kw={"placeholder": "Password"})

    submit = SubmitField("Register")

    def validate_username(self, username):
        existing_user_username = User.query.filter_by(
            username=username.data).first()

        if existing_user_username:
            raise ValidationError(
                "That username already exists. Please choose a different one.")

app.py
from flask import Flask

from login_manager import login_manager
from encryption import bcrypt

from routes import routes_bp
from models import db


app = Flask(__name__)
app.register_blueprint(routes_bp)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///database.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

with open("secret.txt", "r") as file:
    app.config["SECRET_KEY"] = file.read()


if __name__ == "__main__":
    db.app = app
    db.init_app(app)
    db.create_all()  # Create all tables that don't exist yet

    login_manager.init_app(app)
    bcrypt.init_app(app)

    app.run(debug=True)

routes.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_required, login_user, logout_user

from encryption import bcrypt
from forms import LoginForm, RegisterForm
from models import Stats, User, db

routes_bp = Blueprint("routes", __name__, template_folder="templates")


@routes_bp.route("/")
def home():
    if current_user.is_authenticated:
        return redirect(url_for("routes.dashboard"))

    return render_template("home.html")


@routes_bp.route("/dashboard")
@login_required
def dashboard():
    return render_template("dashboard.html")


@routes_bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for("routes.dashboard"))

    return render_template("login.html", form=form)


@routes_bp.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("routes.login"))


@routes_bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        new_user_stats = Stats(money=0)
        new_user = User(username=form.username.data,
                        password=hashed_password, stats=new_user_stats)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for("routes.login"))

    return render_template("register.html", form=form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/base.css')}}">
    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}
<div>
    <h1>You are logged in!</h1>
    <a href="{{url_for('routes.logout')}}">Press here to logout</a>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
<script src="{{url_for('static', filename='scripts/dashboard.js')}}"></script>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div>
    <h1>PythonFlaskAuth</h1>
    <a href="{{url_for('routes.login')}}">Login Page</a><br>
    <a href="{{url_for('routes.register')}}">Register Page</a>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<div>
    <h1>Login page</h1>

    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ form.username }}
        {{ form.password }}
        {{ form.submit }}
    </form>

    <a href="{{url_for('routes.register')}}">Don't have an account?</a>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
<div>
    <h1>Register page</h1>

    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ form.username }}
        {{ form.password }}
        {{ form.submit }}
    </form>

    <a href="{{url_for('routes.login')}}">Already have an account?</a>
</div>
{% endblock %}